apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: exam2025
        image: gcr.io/icai2025/exam2025:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: GCP_BUCKET_NAME
            value: "REPLACE_BUCKET_NAME"
        livenessProbe:
          periodSeconds: 
          httpGet:
            path: /probe
            port: 5000


